var game = new Phaser.Game(800 , 800 , Phaser.AUTO);
game.state.add('state0' , demo.state0);
game.state.add('state1',demo.state1);
game.state.add('state2',demo.state2);
game.state.add('state3',demo.state3);
game.state.add('state4',demo.state4);
game.state.add('state5',demo.state5);
game.state.add('state6',demo.state6);
game.state.add('state7',demo.state7);
game.state.add('state8',demo.state8);
game.state.add('state9',demo.state9);
game.state.add('state10',demo.state10);
game.state.add('state11',demo.state11);
game.state.add('state12',demo.state12);
game.state.add('state13',demo.state13);
game.state.add('state14',demo.state14);
game.state.add('state15',demo.state15);
game.state.add('state16',demo.state16);
game.state.add('state17',demo.state17);
game.state.add('state18',demo.state18);
game.state.add('state19',demo.state19);
game.state.add('state20',demo.state20);
game.state.add('state21',demo.state21);
game.state.add('state22',demo.state22);
game.state.add('state23',demo.state23);
game.state.add('state24',demo.state24);
//game.state.add('state24',demo.state24);
game.state.start('state16');